spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/repo2
    username: root
    password:
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 5050
